// Checks route rendering and action dispatch without pretending to validate a desktop window.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const elements=new Map();
const node=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',classList:{add(){},remove(){}},setAttribute(){},showModal(){this.open=true},close(){this.open=false}});return elements.get(id)};
const context=vm.createContext({console,setTimeout,clearTimeout,setInterval(){},location:{hash:'#home'},localStorage:{getItem(){return null},setItem(){}},window:{addEventListener(){},scrollTo(){}},document:{getElementById:node,querySelectorAll(){return []},addEventListener(){},querySelector(){return {setAttribute(){}}}},fetch:async()=>({ok:true,json:async()=>({products:[],assets:[],skus:[],links:[],tasks:[],batches:[],videos:[],publications:[],sync_tasks:[],download_rules:[],stores:[],templates:['fast_show','product_show'].map(id=>({...JSON.parse(fs.readFileSync(path.join(root,'templates',id+'.json'),'utf8')),id})),settings:{},storage:{total:100,free:100,root:'test',output:'test/output',cache:0}})})});
vm.runInContext(fs.readFileSync(path.join(root,'ui/app.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(path.join(root,'ui/connected.js'),'utf8'),context);
(async()=>{await new Promise(resolve=>setTimeout(resolve,10));for(const route of ['home','shops','products','assets','music','templates','tasks','videos','publish','settings']){vm.runInContext(`location.hash='#${route}';render()`,context);const html=node('page').innerHTML;assert.ok(html.includes('<h1>'),route);assert.ok(!html.includes('undefined'),route+' undefined');console.log('Route render:',route)}console.log('Route rendering passed (not a browser or Windows acceptance test).')})().catch(e=>{console.error(e);process.exitCode=1});
