'use strict';
let online=false, productFocus=null, videoFocus=null;
const selectedProducts=new Set(),selectedAssets=new Set(),selectedVideos=new Set(),selectedMusic=new Set();
const musicModes=[['none','无音乐'],['ai','AI自动选曲（等待接入）'],['single','指定单曲'],['multi','多曲选择']];
const transitionNames={none:'直接切换',fade:'淡入淡出',slideleft:'向左滑动',slideright:'向右滑动',slideup:'向上滑动',slidedown:'向下滑动'};
const motionNames={none:'静止完整展示',zoom:'安全轻微缩放',pan:'安全轻微平移'};
let productStatus='all',storeFilter='',assetKind='all',assetSource='',assetRelation='';
const oldActions=actions,oldRender=render,oldHome=home;
async function api(name,payload){const response=await fetch('/api/'+name,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const r=await response.json();if(!response.ok)throw new Error(r.error||'本地服务连接失败');return r}
async function loadState(redraw=true){const snapshot=await api('state');Object.assign(data,snapshot);templates=snapshot.templates||[];settings={...settings,...snapshot.settings};online=true;if(redraw)render()}
const getProduct=id=>data.products.find(p=>p.id===id);
const getTask=id=>data.tasks.find(p=>p.id===id);
const getAsset=id=>data.assets.find(p=>p.id===id);
const getVideo=id=>data.videos.find(p=>p.id===id);
const getSku=id=>data.skus?.find(p=>p.id===id)?.name||'—';
const productAssets=id=>(data.links||[]).filter(l=>l.product_id===id).sort((a,b)=>a.position-b.position).map(l=>getAsset(l.asset_id)).filter(Boolean);
const media=(a)=>'/media/asset/'+encodeURIComponent(a.id);
const videoURL=v=>'/media/video/'+encodeURIComponent(v.id);
const statusNames={waiting:'等待中',running:'生产中',done:'已完成',failed:'失败',pending:'待发布',uploading:'上传中',uploaded:'已上传',published:'发布成功'};
const statusBadge=s=>`<span class="status ${esc(s)}">${statusNames[s]||esc(s)}</span>`;
const rowtable=(headers,rows,emptyText='暂无记录')=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}" class="table-empty">${emptyText}</td></tr>`}</tbody></table></div>`;
const check=(kind,id)=>`<input type="checkbox" data-select="${kind}" value="${esc(id)}" aria-label="选择 ${esc(id)}" ${(kind==='product'?selectedProducts:kind==='asset'?selectedAssets:selectedVideos).has(id)?'checked':''}>`;
const searchable=(...fields)=>!query||fields.some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()));
const thumbnail=a=>a?.kind==='image'&&a.available!==false?`<img class="thumb" src="${media(a)}" alt="${esc(a.name)}">`:icon(a?.kind==='music'?'music':'video');
const bytes=n=>n>1024**3?(n/1024**3).toFixed(1)+' GB':n>1024**2?(n/1024**2).toFixed(1)+' MB':(n/1024).toFixed(1)+' KB';
const pstatus=id=>{const ts=data.tasks.filter(t=>t.product_id===id);return ts.some(t=>t.status==='running')?'running':ts.some(t=>t.status==='waiting')?'waiting':ts.some(t=>t.status==='failed')?'failed':ts.length?'done':'unproduced'};
function updateStorage(){if(!data.storage)return;document.getElementById('storage-caption').textContent=bytes(data.storage.total-data.storage.free)+' / '+bytes(data.storage.total)}
render=function(){oldRender();updateStorage()};
save=async function(){try{await api('settings',settings);toast('默认配置已保存');await loadState(false)}catch(e){toast(e.message)}};
config=function(){const t=templates.find(t=>t.id===settings.template)||templates[0];return panel('当前生产配置',`<div class="field"><label class="label">素材来源</label>${select('source',[['local','本地素材'],['products','商品库'],['tiktok','TikTok 店铺商品']],settings.source)}</div><div class="field"><label class="label">店铺选择</label><select aria-label="店铺选择" disabled><option>${settings.source==='tiktok'?'等待连接店铺':'按选定商品关联'}</option></select></div><div class="field"><label class="label">生产范围</label>${go('选择商品 / 素材',settings.source==='local'?'assets':'products')}</div><p class="note">已选择 ${settings.source==='local'?selectedAssets.size+' 份素材':selectedProducts.size+' 个商品'}</p><label class="label">生产模板</label><a href="#templates" class="selected-template"><div class="mini-frame">${icon('image')}</div><div><h3>${esc(t?.name||'请选择模板')}</h3><span>查看或更换生产规则</span></div>${icon('arrow')}</a><div class="field"><label class="label">视频比例</label><select aria-label="视频比例"><option>9:16 · 1080 × 1920</option></select></div><div class="field"><label class="label">视频时长</label>${select('duration',[['template','跟随模板'],['15','15 秒'],['30','30 秒']],settings.duration)}</div><div class="field"><label class="label">音乐规则</label>${select('music',musicModes,settings.music)}</div><div class="field"><label class="label">输出目录</label><input aria-label="输出目录" readonly value="${esc(data.storage?.output||'')}"></div><p class="note">${settings.music==='ai'?'AI与音乐源等待接入；可在任务中选择手动音乐。':'音乐池、逐图时长和批量版本在创建任务中设置。'}</p>${btn('创建生产任务','create-task','primary',false,'play')}`,btn('保存为默认','save-config','link'),'config')};
home=function(){let html=oldHome();if(data.products.length){const start=html.indexOf('<div class="empty compact">');const end=html.indexOf('</section>',start);if(start>=0&&end>start){const cards=`<div class="product-cards">${data.products.slice(-6).reverse().map(p=>{const a=productAssets(p.id).find(a=>a.kind==='image');return `<a class="product-card" href="#products" data-product-focus="${esc(p.id)}">${a?`<img src="${media(a)}" alt="${esc(p.title)}">`:`<div class="asset-thumb">${icon('box')}</div>`}<b>${esc(p.title)}</b><small>${esc(p.id)}</small></a>`}).join('')}</div>`;html=html.slice(0,start)+cards+html.slice(end)}}const oldTable=table(['任务名称','素材来源','对象数量','模板','状态','进度','开始时间','操作'],'尚未创建生产任务');html=html.replace(oldTable,taskRows(data.tasks.slice(-5).reverse()));html=html.replace('生产任务 <span class="note">(0)</span>',`生产任务 <span class="note">(${data.tasks.length})</span>`);return html};
products=function(){const shown=data.products.filter(p=>searchable(p.id,p.title,...(data.skus||[]).filter(s=>s.product_id===p.id).map(s=>s.name))).filter(p=>(!storeFilter||p.store===storeFilter)&&(productStatus==='all'||pstatus(p.id)===productStatus));const p=getProduct(productFocus);const rows=shown.map(p=>`<tr class="${p.id===productFocus?'row-selected':''}"><td>${check('product',p.id)}</td><td>${btn(`<b>${esc(p.id)}</b>`,'focus-product:'+p.id,'row-link')}<span class="row-sub">${esc(p.title)}</span></td><td>${esc(p.store)||'—'}</td><td>${data.skus.filter(s=>s.product_id===p.id).length}</td><td>${productAssets(p.id).length}</td><td>${data.tasks.filter(t=>t.product_id===p.id&&t.status==='done').length}</td><td>${pstatus(p.id)==='unproduced'?'<span class="note">未生产</span>':statusBadge(pstatus(p.id))}</td><td>${btn('管理','focus-product:'+p.id,'link')}</td></tr>`).join('');return heading('商品库','统一管理商品、SKU、关联素材与生成视频',btn('导入商品','import-products','',false,'download')+btn('新建商品','new-product','primary',false,'plus'))+`<div class="toolbar">${search('搜索商品编号、标题或 SKU…')}<div class="filters"><select id="store-filter" aria-label="店铺筛选"><option value="">全部店铺</option>${data.stores.map(s=>`<option ${storeFilter===s?'selected':''}>${esc(s)}</option>`).join('')}</select><select id="production-filter" aria-label="生产状态筛选">${[['all','全部生产状态'],['unproduced','未生产'],['waiting','等待中'],['running','生产中'],['done','已生成'],['failed','失败']].map(([s,n])=>`<option value="${s}" ${productStatus===s?'selected':''}>${n}</option>`).join('')}</select></div></div><div class="split">${panel(`全部商品 <span class="note">(${data.products.length})</span>`,rowtable(['选择','商品编号 / 标题','店铺','SKU','素材','视频','生产状态','操作'],rows,noRecords())+(!data.products.length?empty('添加你的第一个商品','商品可关联多个 SKU、多份素材和多条视频。','box',btn('新建商品','new-product','primary',false,'plus'),'compact'):'')+`<div class="footer-actions"><span>已选择 ${selectedProducts.size} 个商品</span>${btn('创建生产任务','product-tasks','',!selectedProducts.size,'play')}</div>`)}${panel('商品关联信息',p?`<h3>${esc(p.title)}</h3><dl class="detail-list"><dt>商品 ID</dt><dd>${esc(p.id)}</dd><dt>店铺</dt><dd>${esc(p.store)||'—'}</dd><dt>商品链接</dt><dd>${esc(p.url)||'—'}</dd><dt>SKU</dt><dd>${data.skus.filter(s=>s.product_id===p.id).map(s=>esc(s.name)).join('<br>')||'—'}</dd></dl><div class="divider"></div><h3>关联素材 (${productAssets(p.id).length})</h3><div class="detail-assets">${productAssets(p.id).map(a=>thumbnail(a)).join('')}</div><div class="actions">${btn('关联素材','link-assets:'+p.id,'',false,'link')}${btn('编辑商品','edit-product:'+p.id,'')}</div>`:`<div class="detail-empty">${icon('box')}<span>选择商品，查看关联信息</span></div>`)}</div>`};
assets=function(){let shown=data.assets.filter(a=>!a.deleted&&searchable(a.name)).filter(a=>(tab==='all'||a.kind===tab)&&(!assetSource||a.source===assetSource)&&(!assetRelation||(assetRelation==='linked')===data.links.some(l=>l.asset_id===a.id)));const body=view==='grid'?`<div class="asset-grid">${shown.map(a=>`<article class="asset-card"><div class="asset-thumb">${a.kind==='image'?`<img src="${media(a)}" alt="${esc(a.name)}">`:icon(a.kind==='music'?'music':'video')}</div><div class="asset-meta"><label>${check('asset',a.id)}<span title="${esc(a.name)}">${esc(a.name)}</span></label><small>${bytes(a.size)} · ${a.source==='local'?'本地导入':'店铺下载'}</small>${btn('预览','preview-asset:'+a.id,'link')}</div></article>`).join('')}</div>`:rowtable(['选择','素材名称','类型','来源','关联商品','大小','操作'],shown.map(a=>`<tr><td>${check('asset',a.id)}</td><td>${esc(a.name)}</td><td>${{image:'图片',video:'视频',music:'音乐'}[a.kind]}</td><td>${a.source==='local'?'本地':'店铺'}</td><td>${data.links.filter(l=>l.asset_id===a.id).map(l=>esc(l.product_id)).join(', ')||'未绑定'}</td><td>${bytes(a.size)}</td><td>${btn('预览','preview-asset:'+a.id,'link')}</td></tr>`).join(''),noRecords());return heading('素材中心','图片、视频与音乐统一管理，保留原名，可不绑定商品',btn('导入文件夹','import-folder','',false,'folder')+btn('导入素材','import','primary',false,'plus'))+`<div class="toolbar">${search('搜索素材名称…')}<div class="filters"><select id="asset-source" aria-label="素材来源">${[['','全部来源'],['local','本地导入'],['tiktok','TikTok 下载']].map(([v,n])=>`<option value="${v}" ${assetSource===v?'selected':''}>${n}</option>`).join('')}</select><select id="asset-relation" aria-label="关联状态">${[['','全部关联状态'],['linked','已绑定商品'],['unlinked','未绑定商品']].map(([v,n])=>`<option value="${v}" ${assetRelation===v?'selected':''}>${n}</option>`).join('')}</select><div class="view-toggle">${btn(icon('grid'),'view:grid',view==='grid'?'active':'')}${btn(icon('list'),'view:list',view==='list'?'active':'')}</div></div></div><div class="panel">${tabs([['all','全部素材',data.assets.length],...['image','video','music'].map(k=>[k,{image:'图片',video:'视频',music:'音乐'}[k],data.assets.filter(a=>a.kind===k).length])])}${shown.length?body:empty(query?noRecords():'导入本地生产素材','图片、视频和音乐使用同一素材体系。','folder',btn('导入素材','import','primary',false,'plus'),'wide')}<div class="footer-actions"><span>已选择 ${selectedAssets.size} 份素材</span><div class="actions">${btn('关联商品','assets-link','',!selectedAssets.size,'link')}${btn('创建生产任务','asset-tasks','',!selectedAssets.size,'play')}</div></div></div>`};
function taskRows(tasks){return rowtable(['任务 / 商品','SKU','素材','模板','状态','进度','输出 / 原因','操作'],tasks.map(t=>`<tr><td><b class="row-title">${esc(data.batches.find(b=>b.id===t.batch_id)?.name||t.id)}</b><small class="row-sub">${esc(t.product_id||'独立素材组')}</small></td><td>${esc(getSku(t.sku_id))}</td><td>${JSON.parse(t.assets).length}</td><td>${esc(templates.find(x=>x.id===t.template)?.name||t.template)}</td><td>${statusBadge(t.status)}</td><td><progress class="progress" max="100" value="${t.progress}"></progress>${t.progress}%</td><td><span class="row-sub" title="${esc(t.error||t.output||'')}">${esc(t.error||t.output||'—')}</span></td><td>${t.status==='failed'?btn('重试','retry:'+t.id,'link'):t.status==='done'?go('查看视频','videos','link'):''}</td></tr>`).join(''),noRecords())}
taskPage=function(){return heading('生产任务','每个生产对象 × 每个模板版本，生成独立视频任务',btn('创建生产任务','create-task','primary',false,'plus'))+countStats()+`<div class="panel">${tabs([['all','全部任务',data.tasks.length],...['waiting','running','done','failed'].map(s=>[s,statusNames[s],data.tasks.filter(t=>t.status===s).length])])}<div class="toolbar">${search('搜索任务、商品编号…')}</div>${taskRows(data.tasks.filter(t=>(tab==='all'||t.status===tab)&&searchable(t.product_id,t.id,data.batches.find(b=>b.id===t.batch_id)?.name)).slice().reverse())}</div>`};
const videoTask=v=>getTask(v.task_id);
function publicationRows(){return rowtable(['视频 / 商品','SKU','发布目标','发布状态','失败原因 / 说明','时间','操作'],data.publications.filter(p=>(route!=='publish'||tab==='all'||p.status===tab)&&searchable(p.id,videoTask(getVideo(p.video_id)||{})?.product_id,p.target)).map(p=>{const v=getVideo(p.video_id),t=v&&videoTask(v);return `<tr><td>${esc(t?.product_id||'独立素材视频')}<small class="row-sub">${esc(v?.path||'')}</small></td><td>${esc(getSku(t?.sku_id))}</td><td>${esc(p.target)||'等待连接环境'}</td><td>${statusBadge(p.status)}</td><td><span class="row-sub">${esc(p.error||'—')}</span></td><td>${esc(p.created)}</td><td>${btn('重新执行','','',true,'refresh')}</td></tr>`}).join(''),'暂无发布任务')}
publicationQueue=function(){return panel('发布任务队列',`<p class="note">等待真实环境连接；视频生成成功不会自动标记为发布成功。</p>${publicationRows()}`,go('发布中心','publish','link','arrow'))};
function vstate(v){const ps=data.publications.filter(p=>p.video_id===v.id);return ps.some(p=>p.status==='published')?'published':ps.some(p=>p.status==='failed')?'failed':'pending'}
videoPage=function(){const shown=data.videos.filter(v=>tab==='trash'?v.trashed:!v.trashed&&(tab==='all'||(tab==='published'?vstate(v)==='published':vstate(v)===tab))).filter(v=>{const t=videoTask(v),p=getProduct(t?.product_id);return searchable(t?.product_id,p?.title,getSku(t?.sku_id))});const v=getVideo(videoFocus),t=v&&videoTask(v),p=t&&getProduct(t.product_id);return flow('videos')+heading('视频管理','管理已生成视频，预览、追溯来源并加入发布任务',btn('导出列表','export-videos','',!data.videos.length,'download'))+`<div class="toolbar">${search('搜索商品编号、标题或 SKU…')}${btn('批量加入发布','queue-selected','primary',!selectedVideos.size,'send')}</div><div class="split"><div class="panel">${tabs([['all','全部视频',data.videos.filter(v=>!v.trashed).length],['pending','待发布',data.videos.filter(v=>!v.trashed&&vstate(v)==='pending').length],['published','已发布',data.videos.filter(v=>!v.trashed&&vstate(v)==='published').length],['failed','发布失败',data.videos.filter(v=>!v.trashed&&vstate(v)==='failed').length],['trash','回收站',data.videos.filter(v=>v.trashed).length]])}${rowtable(['选择','预览','商品信息','SKU','时长','生成时间','状态','操作'],shown.map(v=>{const t=videoTask(v),p=getProduct(t.product_id),a=getAsset(JSON.parse(t.assets)[0]);return `<tr class="${videoFocus===v.id?'row-selected':''}"><td>${check('video',v.id)}</td><td>${btn(thumbnail(a),'focus-video:'+v.id,'link')}</td><td><b>${esc(t.product_id||'独立素材组')}</b><small class="row-sub">${esc(p?.title||v.path)}</small></td><td>${esc(getSku(t.sku_id))}</td><td>${v.duration.toFixed(1)} 秒</td><td>${esc(v.created)}</td><td>${!v.available?'<span class="note">文件已清理或缺失</span>':v.trashed?'<span class="note">回收站</span>':statusBadge(vstate(v))}</td><td>${v.trashed?btn('恢复','restore:'+v.id,'link'):btn('查看','focus-video:'+v.id,'link')}</td></tr>`}).join(''),noRecords())}${!data.videos.length?empty('生成的视频将显示在这里','视频保留实际使用的素材、模板及任务记录。','video',go('前往生产任务','tasks','','tasks'),'compact'):''}<div class="footer-actions"><span>已选择 ${selectedVideos.size} 个视频</span>${btn('移入回收站','trash-selected','danger',!selectedVideos.size,'trash')}</div></div><div class="panel"><h3>视频预览与关联信息</h3><div class="video-preview">${v?.available?`<video controls preload="metadata" src="${videoURL(v)}"></video>`:icon('play')}</div><dl class="detail-list">${[['商品编号',t?.product_id],['商品标题',p?.title],['SKU',getSku(t?.sku_id)],['模板',templates.find(x=>x.id===t?.template)?.name],['生产任务',t?.id],['生成时间',v?.created],['文件路径',v?v.resolved_path||v.path:null],['商品链接',p?.url]].map(([k,val])=>`<dt>${k}</dt><dd>${esc(val||'—')}</dd>`).join('')}</dl><div class="divider"></div><h3>原始素材 (${t?JSON.parse(t.assets).length:0})</h3><div class="detail-assets">${t?JSON.parse(t.assets).map(getAsset).filter(Boolean).map(thumbnail).join(''):''}</div><div class="actions">${btn('打开文件','open-video:'+(v?.id||''),'',!v?.available,'folder')}${btn('重新生成','regenerate:'+(v?.id||''),'',!v,'refresh')}</div></div></div>${v?videoDetails(v):''}${publicationQueue()}`};
publishPage=function(){return heading('发布中心','独立记录上传状态与最终发布结果',`<span class="status waiting">等待连接 TikTok 店铺环境</span>`)+`<div class="info-banner">${icon('clock')}尚未执行真实上传或发布。队列保留到环境接入后继续处理。</div><div class="panel">${tabs([['all','全部任务',data.publications.length],...['pending','uploading','uploaded','published','failed'].map(s=>[s,statusNames[s],data.publications.filter(p=>p.status===s).length])])}<div class="toolbar">${search('搜索商品或发布任务…')}${btn('开始发布','','primary',true,'send')}</div>${publicationRows()}${data.publications.length?'':empty('从视频管理添加发布任务','视频生成与发布状态分别记录。','send',go('选择视频','videos','','video'),'compact')}</div>`};
settingsPage=function(){return heading('设置','保存默认生产规则和真实文件保留策略',btn('保存设置','save-settings','primary'))+`<div class="settings-grid">${panel('输出与缓存',`<label class="label">默认输出目录</label><input id="settings-output" readonly value="${esc(settings.output_dir||data.storage?.output||'')}">${btn('选择输出目录','pick-default-output')}${btn('打开输出目录','open-output')}<label class="label">缓存保留</label>${select('cacheDays',[['1','1天'],['7','7天'],['30','30天'],['0','不自动清理']],settings.cacheDays)}${btn('按保存策略清理','cleanup')}<p class="note">当前缓存 ${bytes(data.storage?.cache||0)}；原始素材永不自动删除。</p>`)}${panel('默认生产与音乐',`<label class="label">模板</label>${select('template',templates.map(t=>[t.id,t.name]),settings.template)}<label class="label">音乐模式</label>${select('music',musicModes,settings.music)}${go('管理音乐池','music')}<p class="note">逐图时长、版本、顺序和音乐参数可在创建任务中保存为默认方案。</p>`)}${panel('文件保留',`<label class="label">店铺下载素材</label>${select('download_retention',[['keep','保留'],['after_tasks','相关任务全部成功后删除']],settings.download_retention||'keep')}<label class="label">输出视频</label>${select('output_retention',[['keep','保留'],['after_uploaded','所有发布任务真实上传完成后删除'],['after_published','所有发布任务真实发布成功后删除']],settings.output_retention||'keep')}<p class="note">待执行、运行、失败待重试的素材受保护。没有真实上传结果不会触发输出删除。删除后仍保留记录。</p>`)}${panel('外部服务',`<p>TikTok连接、采集、下载、上传：等待真实浏览器环境。</p><p>AI文案、AI选曲、Pixabay搜索下载：等待接入。</p><button disabled title="服务尚未接入">连接执行不可用</button>`)}</div>`};
function musicPage(){
 const all=data.assets.filter(a=>a.kind==='music');
 const shown=all.filter(a=>searchable(a.name,a.metadata?.title,a.metadata?.author,a.metadata?.tags));
 return heading('音乐中心','导入、试听和管理同一素材库中的音乐；未知作者、来源与授权不作推测',btn('导入音乐','import','primary'))+`<div class="toolbar">${search('搜索曲名、文件名、作者或标签…')}${btn('用于任务','use-music','primary',!selectedMusic.size)}</div><p class="note">已选 ${selectedMusic.size} 首，按勾选顺序组成音乐池。AI自动找歌、Pixabay搜索下载等待接入。</p>`+panel('统一音乐库',rowtable(['选择','音乐名称 / Music_ID','作者 / 时长','来源 / 授权','试听','操作'],shown.map(a=>`<tr><td><input type="checkbox" data-select="music" value="${a.id}" aria-label="选择音乐 ${esc(a.name)}" ${selectedMusic.has(a.id)?'checked':''} ${!a.available?'disabled':''}></td><td><b>${esc(a.metadata?.title||a.name)}</b><small class="row-sub">${esc(a.name)}<br>${a.id}</small></td><td>${esc(a.metadata?.author||'未知')}<br>${Number(a.metadata?.duration||0).toFixed(1)}秒</td><td>${esc(a.source)}<small class="row-sub">${esc(a.metadata?.source_url||'未提供来源链接')}<br>${esc(a.metadata?.license||'未提供授权信息')}</small></td><td>${a.available?`<audio controls preload="none" src="${media(a)}" aria-label="试听 ${esc(a.name)}"></audio>`:'文件已清理或缺失'}</td><td>${btn('信息','music-info:'+a.id,'link')}${btn('使用历史','music-history:'+a.id,'link')}${btn('删除副本','delete-music:'+a.id,'danger',!a.available)}</td></tr>`).join(''),'尚未导入音乐'));
}
function contentFields(c){return `<label>Caption<textarea id="copy-caption">${esc(c.caption||'')}</textarea></label><label>#标签<input id="copy-tags" value="${esc(c.tags||'')}"></label><label>开头文案<input id="copy-opening" value="${esc(c.opening||'')}"></label><label>CTA<input id="copy-cta" value="${esc(c.cta||'')}"></label><label>封面文字<input id="copy-cover" value="${esc(c.cover||'')}"></label><label>发布商品关联<select id="copy-association">${options([['none','不关联商品'],['source','使用明确来源关系'],['selected','指定商品']],c.association||'none')}</select></label><select id="copy-products" multiple aria-label="指定发布商品">${data.products.map(p=>`<option value="${esc(p.id)}" ${(c.product_ids||[]).includes(p.id)?'selected':''}>${esc(p.id)} · ${esc(p.title)}</option>`).join('')}</select><p class="note">来源与发布挂载分开保存；平台实际挂载能力等待验证。AI文案等待接入。</p><button disabled title="AI服务尚未接入">AI生成文案（等待接入）</button>`}
function readContent(){return {caption:value('copy-caption')||'',tags:value('copy-tags')||'',opening:value('copy-opening')||'',cta:value('copy-cta')||'',cover:value('copy-cover')||'',association:value('copy-association')||'none',product_ids:[...(document.getElementById('copy-products')?.selectedOptions||[])].map(e=>e.value)}}
function videoDetails(v){const t=videoTask(v),cfg=JSON.parse(t.config),c=JSON.parse(v.content||'{}'),check=JSON.parse(v.validation||'{}'),m=cfg.music_snapshot;
 return panel('实际配置与发布文字',`<div class="two-fields"><div><p>模板：${esc(cfg.name||t.template)} · 版本 ${cfg.version||1} · 任务变体 ${cfg.variant||1}</p><p>逐图秒数：${esc((cfg.durations||[]).join('、'))}</p><p>音乐：${esc(m?.title||m?.filename||'无音乐')}<br>Music_ID：${esc(cfg.music_id||'—')}<br>来源：${esc(m?.source||'—')}<br>来源URL：${esc(m?.source_url||'—')}<br>授权：${esc(m?.license||'未提供')}</p><p>系统检查：${check.status==='passed'?'完整解码及输出参数检查通过':'此视频尚无完整自动检查记录'}</p><p>来源商品：${esc([...new Set((cfg.source_relations||[]).map(r=>r.product_id))].join('、')||'无商品来源')}</p><p>输出：${esc(v.resolved_path||v.path)}</p></div><div><p>Caption：${esc(c.caption||'未填写')}</p><p>标签：${esc(c.tags||'未填写')}</p><p>开头：${esc(c.opening||'未填写')}</p><p>CTA：${esc(c.cta||'未填写')}</p><p>封面文字：${esc(c.cover||'未填写')}</p><p>发布关联：${esc(c.association||'none')} ${esc((c.product_ids||[]).join('、'))}</p>${btn('编辑发布文字与关联','edit-copy:'+v.id)}${btn('打开所在目录','open-folder:'+v.id,'',!v.available)}</div></div>`);
}
function templateForm(){modal('保存自己的模板',`<label>名称<input id="template-name"></label><label>默认每份素材秒数<input type="number" min="0.034" max="600" step="0.1" id="template-seconds" value="2"></label><label>转场<select id="template-transition">${options(Object.entries(transitionNames),'fade')}</select></label><label>转场秒数<input type="number" min="0" step="0.1" id="template-transition-time" value="0.3"></label><label>运动<select id="template-motion">${options(Object.entries(motionNames),'none')}</select></label><label>默认音乐音量<input type="number" min="0" max="1" step="0.05" id="template-volume" value="0.65"></label>`,btn('取消','close')+btn('保存模板','submit-template','primary'))}

const closeModal=()=>document.getElementById('dialog').close();
function productForm(p={}){modal(p.id?'编辑商品':'新建商品',`<div class="two-fields"><div class="field"><label class="label" for="product-id">商品 ID *</label><input id="product-id" required maxlength="150" value="${esc(p.id||'')}" ${p.id?'readonly':''}></div><div class="field"><label class="label" for="store">店铺</label><input id="store" value="${esc(p.store||'')}" placeholder="可留空"></div></div><div class="field"><label class="label" for="product-title">商品标题 *</label><input id="product-title" required maxlength="1000" value="${esc(p.title||'')}"></div><div class="field"><label class="label" for="product-link">商品链接</label><input id="product-link" value="${esc(p.url||'')}" placeholder="可留空"></div><div class="field"><label class="label" for="sku">SKU（每行一个）</label><textarea id="sku">${data.skus.filter(s=>s.product_id===p.id).map(s=>esc(s.name)).join('\n')}</textarea></div><p class="note">已有 SKU 及历史视频关联保留，新填写的 SKU 将追加。</p>`,btn('取消','close')+btn('保存商品','submit-product','primary'))}
let batchDraft=null,batchSeed=0;
const value=id=>document.getElementById(id)?.value;
const selected=name=>[...document.querySelectorAll(`[name="${name}"]:checked`)].map(e=>e.value);
const options=(items,current)=>items.map(([id,label])=>`<option value="${esc(id)}" ${id===current?'selected':''}>${esc(label)}</option>`).join('');
function batchModal(){
 const draft=batchDraft||settings.production||{};
 batchSeed=Math.floor(Math.random()*2147483647);
 const product=settings.source!=='local';
 const choices=product?data.products:data.assets.filter(a=>a.kind!=='music'&&a.available);
 const chosen=product?selectedProducts:selectedAssets;
 modal('创建批量生产任务',`
 <div class="two-fields"><label>批次名称<input id="task-name" value="${esc(draft.name||'')}"></label><label>生产对象<select id="batch-source">${options([['products','商品库'],['local','本地素材']],product?'products':'local')}</select></label></div>
 <div class="actions">${btn('全选','batch-all')}${btn('取消全选','batch-none')}</div>
 <div class="choice-list">${choices.map(o=>`<label><input type="checkbox" name="batch-object" value="${esc(o.id)}" ${chosen.has(o.id)?'checked':''}><span>${esc(o.title||o.name)}</span>${product?`<select data-sku-for="${esc(o.id)}" aria-label="${esc(o.id)} 的SKU"><option value="">整个商品</option>${data.skus.filter(x=>x.product_id===o.id).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select>`:''}</label>`).join('')||'<p>没有可用对象，请先导入素材或商品。</p>'}</div>
 <div class="two-fields"><label>组合方式<select id="group-mode">${options([['individual',product?'每个商品分别生成':'每份素材分别生成'],['group',product?'所选商品合为一个合集':'所选素材合为一组']],draft.group_mode||'individual')}</select></label><label>素材顺序<select id="batch-order">${options([['selected','按下方指定顺序'],['reverse','反向'],['random','仅在本次素材内随机']],draft.order||'selected')}</select></label></div>
 <p class="group-label">模板（可多选；配置是默认值，任务设置优先）</p>
 <div class="choice-list">${templates.map(t=>`<label><input type="checkbox" name="batch-template" value="${t.id}" ${(draft.templates||[settings.template]).includes(t.id)?'checked':''}>${esc(t.name)} · 默认每份${t.duration_per_image}秒</label>`).join('')}</div>
 <div class="two-fields"><label>版本组合<select id="batch-combination">${options([['all','所有选定模板 × 每模板数量'],['cycle','按所选模板轮流分配'],['random','仅在所选模板内随机分配']],draft.combination||'all')}</select></label><label>每对象数量（全部模板模式为每模板数量）<input type="number" min="1" max="1000" step="1" id="batch-copies" value="${draft.copies||1}"></label></div>
 <div class="two-fields"><label>时长模式<select id="batch-timing">${options([['images','逐图时长（优先于模板）'],['total','指定总时长（均分素材）']],draft.timing||'images')}</select></label><label>总时长（秒）<input type="number" min="0.1" step="0.1" id="batch-total" value="${draft.total_duration||15}"></label></div>
 <label>统一展示秒数（留空跟随模板；下方单图值优先）<input type="number" min="0.034" max="600" step="0.1" id="batch-seconds" value="${draft.image_duration??''}"></label>
 <div id="batch-assets"></div>
 <div class="two-fields"><label>转场<select id="batch-transition">${options([['template','跟随模板'],...Object.entries(transitionNames)],draft.overrides?.transition||'template')}</select></label><label>转场秒数（留空跟随模板）<input type="number" min="0" step="0.1" id="batch-transition-time" value="${draft.overrides?.transition_duration??''}"></label></div>
 <label>画面运动<select id="batch-motion">${options([['template','跟随模板'],...Object.entries(motionNames)],draft.overrides?.motion||'template')}</select></label>
 <div class="two-fields"><label>音乐模式<select id="batch-music">${options(musicModes,draft.music||settings.music||'none')}</select></label><label>多曲分配<select id="batch-music-order">${options([['cycle','按勾选顺序循环'],['random','选定池内随机，避免相邻重复']],draft.music_order||settings.music_order||'cycle')}</select></label></div>
 <p class="note">AI自动选曲与音乐源等待接入。手动模式直接使用下方音乐池。</p>
 <div class="choice-list">${data.assets.filter(a=>a.kind==='music'&&a.available).map(a=>`<label><input type="checkbox" name="batch-song" value="${a.id}" ${(draft.music_ids||settings.music_ids||[...selectedMusic]).includes(a.id)?'checked':''}><span>${esc(a.metadata?.title||a.name)}</span><audio controls preload="none" src="${media(a)}" aria-label="试听 ${esc(a.name)}"></audio></label>`).join('')||'音乐库为空，可无音乐生成。'}</div>
 <div class="two-fields"><label>音乐长度<select id="batch-playback">${options([['loop','循环至视频结束'],['trim','播放一次，短于视频则补静音']],draft.music_playback||'loop')}</select></label><label>音量（0～1）<input type="number" min="0" max="1" step="0.05" id="batch-volume" value="${draft.overrides?.music_volume??.65}"></label></div>
 <label>淡入、淡出各几秒<input type="number" min="0" step="0.1" id="batch-fade" value="${draft.music_fade||0}"></label>
 <label>输出目录<input id="batch-output" readonly value="${esc(draft.output_dir||settings.output_dir||data.storage.output)}"></label>${btn('选择目录','pick-batch-output')}
 <details><summary>发布文字及商品关联（可选）</summary>${contentFields(draft.content||{})}</details>
 <div id="batch-count" class="info-banner"></div><div id="batch-preview" class="note"></div>`,
 btn('保存为默认方案','save-production')+btn('检查预计结果','preview-batch')+btn('取消','close')+btn('创建并开始生产','submit-batch','primary',!choices.length));
 refreshBatchAssets(draft);
 document.getElementById('batch-source').addEventListener('change',e=>{settings.source=e.target.value;batchDraft=null;closeModal();batchModal()});
 document.querySelectorAll('[name=batch-object],[data-sku-for]').forEach(e=>e.addEventListener('change',()=>refreshBatchAssets()));
 document.querySelectorAll('[name=batch-template],#group-mode,#batch-copies,#batch-combination,#batch-timing,#batch-music').forEach(e=>e.addEventListener('change',updateBatchCount));
 // Selection order is preserved in the request, independently of display sorting.
 const songOrder=[...(draft.music_ids||settings.music_ids||[...selectedMusic])];
 document.querySelectorAll('[name=batch-song]').forEach(e=>e.addEventListener('change',()=>{const i=songOrder.indexOf(e.value);if(i>=0)songOrder.splice(i,1);if(e.checked)songOrder.push(e.value);document.getElementById('batch-music').dataset.songOrder=JSON.stringify(songOrder)}));
 document.getElementById('batch-music').dataset.songOrder=JSON.stringify(songOrder);
 updateBatchCount();
}
function batchVisuals(){
 const ids=selected('batch-object');
 if(value('batch-source')==='local')return ids.map(getAsset).filter(Boolean);
 const result=[];
 for(const id of ids){const sku=[...document.querySelectorAll('[data-sku-for]')].find(e=>e.dataset.skuFor===id)?.value;
  for(const l of data.links.filter(l=>l.product_id===id&&(!sku||!l.sku_id||l.sku_id===sku)).sort((a,b)=>a.position-b.position)){
   const a=getAsset(l.asset_id);if(a?.kind!=='music'&&a?.available&&!result.some(x=>x.id===a.id))result.push(a);
  }
 }
 return result;
}
function refreshBatchAssets(draft={}){
 const old={...draft.asset_durations};document.querySelectorAll('[data-duration]').forEach(e=>{if(e.value!=='')old[e.dataset.duration]=e.value});
 const list=batchVisuals();
 document.getElementById('batch-assets').innerHTML=rowtable(['素材','顺序','单独秒数（留空用统一值）'],list.map((a,i)=>`<tr><td>${esc(a.name)}</td><td><input type="number" min="1" data-order="${a.id}" aria-label="${esc(a.name)}顺序" value="${(draft.asset_order||[]).includes(a.id)?draft.asset_order.indexOf(a.id)+1:i+1}"></td><td><input type="number" min="0.034" max="600" step="0.1" data-duration="${a.id}" aria-label="${esc(a.name)}秒数" value="${old[a.id]??''}"></td></tr>`).join(''),'选择对象后显示实际素材');
 updateBatchCount();
}
function updateBatchCount(){
 const n=value('group-mode')==='group'?(selected('batch-object').length?1:0):selected('batch-object').length;
 const m=selected('batch-template').length,c=Number(value('batch-copies'))||0;
 document.getElementById('batch-count').textContent=`${n}个对象 × ${value('batch-combination')==='all'?m+'个模板 × ':''}${c}份 = ${n*c*(value('batch-combination')==='all'?m:1)}条视频任务。预计时长以“检查预计结果”为准。`;
 const total=value('batch-timing')==='total';document.getElementById('batch-total').disabled=!total;
 document.getElementById('batch-seconds').disabled=total;document.querySelectorAll('[data-duration]').forEach(e=>e.disabled=total);
 const submit=document.querySelector('[data-action="submit-batch"]');if(submit)submit.disabled=!n||!m||value('batch-music')==='ai';
}
function readBatch(){
 const ids=selected('batch-object'),product=value('batch-source')==='products',group=value('group-mode')==='group';
 const sku=id=>[...document.querySelectorAll('[data-sku-for]')].find(e=>e.dataset.skuFor===id)?.value||null;
 if(product&&group&&ids.some(id=>sku(id)))throw new Error('商品合集使用整个商品；请清除单SKU选择后创建');
 const objects=product?(group?[{product_ids:ids}]:ids.map(id=>({product_id:id,sku_id:sku(id)}))):(group?[{assets:ids}]:ids.map(id=>({assets:[id]})));
 const overrides={music_volume:Number(value('batch-volume'))};
 if(value('batch-transition')!=='template')overrides.transition=value('batch-transition');
 if(value('batch-transition-time')!=='')overrides.transition_duration=Number(value('batch-transition-time'));
 if(value('batch-motion')!=='template')overrides.motion=value('batch-motion');
 const durations=Object.fromEntries([...document.querySelectorAll('[data-duration]')].filter(e=>e.value!=='').map(e=>[e.dataset.duration,Number(e.value)]));
 const timing=value('batch-timing');
 if(timing==='total'&&(value('batch-seconds')!==''||Object.keys(durations).length))throw new Error('总时长与已填写逐图时间冲突；请切回逐图模式，或清空逐图设置后指定总时长');
 const checked=selected('batch-song'),songOrder=JSON.parse(document.getElementById('batch-music').dataset.songOrder||'[]');
 return {seed:batchSeed,name:value('task-name'),objects,templates:selected('batch-template'),copies:Number(value('batch-copies')),group_mode:value('group-mode'),combination:value('batch-combination'),order:value('batch-order'),asset_order:[...document.querySelectorAll('[data-order]')].sort((a,b)=>Number(a.value)-Number(b.value)).map(e=>e.dataset.order),timing,total_duration:timing==='total'?Number(value('batch-total')):undefined,image_duration:value('batch-seconds')===''?undefined:Number(value('batch-seconds')),asset_durations:durations,overrides,music:value('batch-music'),music_ids:[...new Set([...songOrder.filter(id=>checked.includes(id)),...checked])],music_order:value('batch-music-order'),music_playback:value('batch-playback'),music_fade:Number(value('batch-fade')),output_dir:value('batch-output'),content:readContent()};
}
actions=async function(action){try{
 if(action==='reconnect'){await loadState();return}
 if(!online && !action.startsWith('go:')){toast('本地工作空间尚未连接');return}
 if(action==='help'){modal('从商品到视频',`<ol class="rules"><li>在商品库新建或导入商品；本地素材可以不绑定商品。</li><li>导入图片、视频和音乐，按需关联商品。</li><li>选定商品或素材，选择模板创建批量任务。</li><li>在视频管理预览、追溯、重新生成或加入发布队列。</li><li>真实 TikTok 环境接入后再执行同步和发布。</li></ol>`);return}
 if(action.startsWith('focus-product:')){productFocus=action.slice(14);render();return}
 if(action.startsWith('focus-video:')){videoFocus=action.slice(12);render();return}
 if(action==='new-product'){productForm();return}
 if(action.startsWith('edit-product:')){productForm(getProduct(action.slice(13)));return}
 if(action==='submit-product'){const value=id=>document.getElementById(id).value.trim();const id=value('product-id'),title=value('product-title');if(!id||!title){toast('请填写商品 ID 和标题');return}await api('product',{id,title,store:value('store'),url:value('product-link'),skus:value('sku').split('\n')});closeModal();productFocus=id;await loadState();toast('商品已保存');return}
 if(action==='import-products'){modal('导入商品 CSV',`<p class="dialog-description">CSV 表头：id、title、store、url、skus。id 与 title 必填；多个 SKU 使用 | 分隔。相同商品 ID 更新信息并保留历史关联。</p>`,btn('取消','close')+btn('选择 CSV 文件','pick-products','primary',false,'folder'));return}
 if(action==='pick-products'){closeModal();const r=await api('import-products',{});if(r.cancelled){toast('已取消选择');return}await loadState();toast(`已导入 ${r.count} 个商品`);return}
 if(['import','import-folder'].includes(action)){const r=await api('import',{folder:action==='import-folder'});if(r.cancelled){toast('已取消选择');return}await loadState();if(r.errors.length){modal('素材导入结果',`<p class="dialog-description">识别 ${r.ids.length} 份有效素材，${r.errors.length} 份未导入。</p><div class="import-result">${r.errors.map(e=>`<p><b>${esc(e.name)}</b><br>${esc(e.error)}</p>`).join('')}</div>`)}else toast(`已识别 ${r.ids.length} 份素材`);return}
 if(action.startsWith('preview-asset:')){const a=getAsset(action.slice(14));modal(esc(a.name),a.kind==='image'?`<img src="${media(a)}" alt="${esc(a.name)}" width="100%">`:a.kind==='music'?`<audio src="${media(a)}" controls></audio>`:`<video src="${media(a)}" controls width="100%"></video>`);return}
 if(action.startsWith('link-assets:')){const pid=action.slice(12);modal('关联素材 · '+esc(pid),`<div class="choice-list">${data.assets.map(a=>`<label><input type="checkbox" name="link-asset" value="${a.id}" ${productAssets(pid).some(x=>x.id===a.id)?'checked disabled':''}><span>${esc(a.name)}</span></label>`).join('')||'<p class="note">请先导入素材。</p>'}</div>`,btn('取消','close')+btn('保存关联','submit-link:'+pid,'primary',!data.assets.length));return}
 if(action.startsWith('submit-link:')){await api('link',{product_id:action.slice(12),ids:[...document.querySelectorAll('[name=link-asset]:checked')].map(e=>e.value)});closeModal();await loadState();toast('素材关联已保存');return}
 if(action==='assets-link'){modal('关联到商品',`<div class="field"><label class="label">目标商品</label><select id="link-product">${data.products.map(p=>`<option value="${esc(p.id)}">${esc(p.id)} · ${esc(p.title)}</option>`).join('')}</select></div><p class="note">将关联 ${selectedAssets.size} 份素材，保留现有商品关系。</p>`,btn('取消','close')+btn('关联','link-selected','primary',!data.products.length));return}
 if(action==='link-selected'){await api('link',{product_id:document.getElementById('link-product').value,ids:[...selectedAssets]});closeModal();await loadState();toast('关联已保存');return}
 if(['create-task','product-tasks','asset-tasks'].includes(action)){if(action==='product-tasks')settings.source='products';if(action==='asset-tasks')settings.source='local';if(settings.source==='tiktok'){toast('等待连接 TikTok 店铺环境');return}batchModal();return}
 if(action==='submit-batch'){const payload=readBatch();const button=document.querySelector('[data-action="submit-batch"]');button.disabled=true;try{const r=await api('batch',payload);batchDraft=null;closeModal();await loadState();location.hash='tasks';toast(`已创建 ${r.tasks} 条任务`)}finally{if(button.isConnected)button.disabled=false}return}
 if(action==='preview-batch'){const r=await api('batch-preview',readBatch());document.getElementById('batch-preview').textContent=r.preview.map((t,i)=>`第${i+1}条：${t.config.expected_duration.toFixed(3)}秒，${t.config.name}，音乐 ${t.config.music_snapshot?.title||'无'}`).join('；');return}
 if(action==='save-production'){const payload=readBatch();const {objects,seed,...defaults}=payload;await api('settings',{production:defaults,music:payload.music,music_ids:payload.music_ids,music_order:payload.music_order});settings.production=defaults;toast('方案已保存；生产对象仍由每次选择决定');return}
 if(action==='batch-all'||action==='batch-none'){document.querySelectorAll('[name=batch-object]').forEach(e=>e.checked=action==='batch-all');refreshBatchAssets();return}
 if(action==='pick-batch-output'||action==='pick-default-output'){const r=await api('choose-output',{});if(r.cancelled){toast('已取消选择');return}if(action==='pick-batch-output')document.getElementById('batch-output').value=r.path;else{settings.output_dir=r.path;document.getElementById('settings-output').value=r.path}return}
 if(action==='new-template'){templateForm();return}
 if(action==='submit-template'){await api('template',{name:value('template-name'),duration_per_image:Number(value('template-seconds')),transition:value('template-transition'),transition_duration:Number(value('template-transition-time')),motion:value('template-motion'),music_volume:Number(value('template-volume'))});closeModal();await loadState();toast('模板已保存');return}
 if(action.startsWith('preview-template:')){if(!selectedAssets.size&&!selectedProducts.size){toast('请先选择用于生成示例的真实素材或商品');return}settings.template=action.slice(17);batchDraft=null;batchModal();return}
 if(action==='use-music'){settings.music=selectedMusic.size===1?'single':'multi';settings.music_ids=[...selectedMusic];settings.production={...settings.production,music:settings.music,music_ids:settings.music_ids};await api('settings',{music:settings.music,music_ids:settings.music_ids,production:settings.production});batchDraft=null;batchModal();return}
 if(action.startsWith('music-info:')){const a=getAsset(action.slice(11));modal('音乐信息（只填写已知资料）',`${['title','author','source_url','license','tags'].map((k,i)=>`<label>${['曲名','作者','来源URL','授权信息','标签'][i]}<input id="music-${k}" value="${esc(a.metadata?.[k]||'')}"></label>`).join('')}<p>Music_ID：${a.id}</p>`,btn('取消','close')+btn('保存','save-music:'+a.id,'primary'));return}
 if(action.startsWith('save-music:')){await api('music-metadata',{id:action.slice(11),values:Object.fromEntries(['title','author','source_url','license','tags'].map(k=>[k,value('music-'+k)]))});closeModal();await loadState();return}
 if(action.startsWith('music-history:')){const id=action.slice(14);const tasks=data.tasks.filter(t=>JSON.parse(t.config).music_id===id);modal('音乐使用历史',rowtable(['任务','状态','保存的曲名与来源'],tasks.map(t=>{const m=JSON.parse(t.config).music_snapshot;return `<tr><td>${esc(t.id)}</td><td>${statusBadge(t.status)}</td><td>${esc(m?.title||getAsset(id)?.name||id)}<br>${esc(m?.source_url||'未提供来源链接')}</td></tr>`}).join(''),'尚未用于任务'));return}
 if(action.startsWith('delete-music:')){const id=action.slice(13);modal('删除音乐副本',`<p>保留用户原文件和使用历史。待执行、运行或待重试任务使用的音乐不能删除。</p>`,btn('取消','close')+btn('删除副本','confirm-delete-music:'+id,'danger'));return}
 if(action.startsWith('confirm-delete-music:')){const id=action.slice(21);await api('delete-asset',{id});selectedMusic.delete(id);closeModal();await loadState();return}
 if(action.startsWith('edit-copy:')){const v=getVideo(action.slice(10));modal('发布文字与商品关联',contentFields(JSON.parse(v.content||'{}')),btn('取消','close')+btn('保存','save-copy:'+v.id,'primary'));return}
 if(action.startsWith('save-copy:')){await api('content',{id:action.slice(10),content:readContent()});closeModal();await loadState();return}
 if(action.startsWith('open-folder:')){await api('open',{id:action.slice(12),folder:true});return}
 if(action==='queue-selected'){modal('加入发布队列',`<label>目标账号／店铺（仅保存配置）<input id="queue-target"></label><p>将保存 ${selectedVideos.size} 条视频及各自文案。真实上传与发布等待接入。</p>`,btn('取消','close')+btn('保存队列','confirm-queue','primary'));return}
 if(action==='confirm-queue'){for(const id of selectedVideos)await api('queue',{id,target:value('queue-target')});closeModal();await loadState();toast('队列已保存，等待真实连接');return}

 if(action.startsWith('retry:')){await api('retry',{id:action.slice(6)});await loadState();return}
 if(action.startsWith('regenerate:')){await api('regenerate',{id:action.slice(11)});await loadState();toast('已按原始配置创建新视频任务');return}
 if(action.startsWith('open-video:')){await api('open',{id:action.slice(11)});return}
 if(action==='open-output'){await api('open',{});return}
 if(action==='trash-selected'){modal('移入回收站',`<p class="dialog-description">将 ${selectedVideos.size} 条视频移入回收站。输出文件暂时保留，原始素材不受影响。</p>`,btn('取消','close')+btn('移入回收站','confirm-trash','danger'));return}
 if(action==='confirm-trash'){for(const id of selectedVideos)await api('trash',{id});selectedVideos.clear();closeModal();await loadState();return}
 if(action.startsWith('restore:')){await api('trash',{id:action.slice(8),restore:true});await loadState();return}
 if(action==='cleanup'){const r=await api('cleanup',{});await loadState();toast('已清理 '+bytes(r.bytes)+' 缓存');return}
 if(action==='export-videos'){const header=['video_id','product_id','sku','template','task_id','path','created'];const rows=data.videos.map(v=>{const t=videoTask(v);return[v.id,t.product_id,getSku(t.sku_id),t.template,t.id,v.resolved_path||v.path,v.created]});const csv='\ufeff'+[header,...rows].map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='TikTokVideoMaker_videos.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return}
 return await oldActions(action);
}catch(e){toast(e.message)}};
document.addEventListener('change',e=>{const kind=e.target.dataset.select;if(kind){const set=kind==='product'?selectedProducts:kind==='asset'?selectedAssets:kind==='music'?selectedMusic:selectedVideos;e.target.checked?set.add(e.target.value):set.delete(e.target.value);render()}if(e.target.id==='store-filter'){storeFilter=e.target.value;render()}if(e.target.id==='production-filter'){productStatus=e.target.value;render()}if(e.target.id==='asset-source'){assetSource=e.target.value;render()}if(e.target.id==='asset-relation'){assetRelation=e.target.value;render()}});
document.addEventListener('click',e=>{const a=e.target.closest('[data-product-focus]');if(a)productFocus=a.dataset.productFocus});
// Refresh only when the user is not editing, selecting, viewing a modal or playing video.
setInterval(async()=>{if(!['home','tasks','videos','publish'].includes(route)||!online||document.getElementById('dialog').open||document.querySelector('video')||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;try{const before=JSON.stringify(data);await loadState(false);if(before!==JSON.stringify(data))render()}catch(e){online=false;toast(e.message+'；可点击重试连接')}},2000);
loadState().catch(e=>{online=false;document.getElementById('page').innerHTML=panel('本地工作空间未连接',`<div class="offline"><h3>请从 TikTokVideoMaker 桌面程序启动</h3><p class="note">${esc(e.message)}</p>${btn('重试连接','reconnect')}</div>`)});
shops=function(){const rules=data.download_rules||[];return heading('店铺商品','选择店铺与商品范围，应用图片下载规则后同步到统一素材中心',`<span class="status waiting">等待连接 TikTok 店铺环境</span>`)+`<div class="info-banner">${icon('clock')}当前仅保存同步配置。没有连接真实环境，不会采集商品或下载图片。</div><div class="settings-grid">${panel('商品同步配置',`<div class="field"><label class="label" for="sync-store">待连接店铺</label><input id="sync-store" placeholder="填写店铺名称，仅保存配置"></div><div class="field"><label class="label" for="sync-scope">商品范围</label><select id="sync-scope"><option value="all">全部商品</option><option value="selected">指定商品 ID</option></select></div><div class="field"><label class="label" for="sync-ids">指定商品 ID（每行一个）</label><textarea id="sync-ids" disabled placeholder="选择指定商品范围后填写"></textarea></div><div class="field"><label class="label" for="sync-rule">图片下载规则</label><select id="sync-rule">${rules.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')||'<option value="">请先保存图片下载规则</option>'}</select></div><div class="actions">${btn('保存待连接配置','save-sync','primary',!rules.length,'check')}${btn('开始同步','','',true,'download')}</div>`)}${panel('图片下载规则',`<div class="field"><label class="label" for="rule-name">规则名称</label><input id="rule-name" placeholder="例如：手机壳视频素材规则"></div><div class="field"><label class="label" for="rule-main">商品主图</label><select id="rule-main"><option value="first">下载第 1 张主图</option><option value="all">下载全部主图</option><option value="custom">自定义选择</option></select></div><div class="field"><label class="label" for="rule-indices">自定义主图序号</label><input id="rule-indices" disabled placeholder="例如：1,3,5"></div><label class="settings-row"><span>全部详情图片</span><input id="rule-details" type="checkbox" checked></label><label class="settings-row"><span>SKU 图片及对应关系</span><input id="rule-skus" type="checkbox" checked></label><label class="settings-row"><span>商品视频 <small class="note">当前未开放</small></span><input type="checkbox" disabled></label><p class="note">保留商品 ID、SKU ID / 名称、图片类型、排序和来源。后续生产直接使用关联素材。</p>${btn('保存下载规则','save-rule','primary',false,'check')}`)}</div>${panel('已保存的图片规则',rowtable(['规则名称','主图','详情图','SKU 图','商品视频','操作'],rules.map(r=>{const c=JSON.parse(r.config);return `<tr><td>${esc(r.name)}</td><td>${c.main==='first'?'第 1 张':c.main==='all'?'全部主图':'第 '+c.indices.join('、')+' 张'}</td><td>${c.details?'全部':'关闭'}</td><td>${c.sku_images?'开启':'关闭'}</td><td>关闭</td><td>${btn('载入规则','load-rule:'+r.id,'link')}</td></tr>`}).join(''),'尚未保存下载规则'))}${panel('商品同步任务',rowtable(['店铺','商品范围','图片规则','同步状态','创建时间'],(data.sync_tasks||[]).map(t=>{const c=JSON.parse(t.rule_snapshot||'{}'),s=JSON.parse(t.product_scope||'{}');return `<tr><td>${esc(t.store)}</td><td>${s.mode==='all'?'全部商品':esc((s.ids||[]).join('、'))}</td><td>${c.main==='first'?'第 1 张主图':c.main==='all'?'全部主图':esc((c.indices||[]).join('、'))}</td><td><span class="status waiting">等待连接</span></td><td>${esc(t.created)}</td></tr>`}).join(''),'暂无同步配置'))}`};
let editingRule=null;
const productionActions=actions;
actions=async function(action){try{
 if(action==='save-rule'){const mode=document.getElementById('rule-main').value;const text=document.getElementById('rule-indices').value.trim();const indices=mode==='custom'?text.split(/[,，\s]+/).filter(Boolean).map(x=>/^\d+$/.test(x)?Number(x):null):[];if(mode==='custom'&&(!indices.length||indices.some(x=>x===null||!Number.isSafeInteger(x)||x<1))){toast('请输入正整数主图序号，例如 1,3,5');return}await api('download-rule',{id:editingRule,name:document.getElementById('rule-name').value,main:mode,indices,details:document.getElementById('rule-details').checked,sku_images:document.getElementById('rule-skus').checked,product_video:false});editingRule=null;await loadState();toast('图片下载规则已保存');return}
 if(action.startsWith('load-rule:')){const r=data.download_rules.find(r=>r.id===action.slice(10));if(!r)return;editingRule=r.id;const c=JSON.parse(r.config);document.getElementById('rule-name').value=r.name;document.getElementById('rule-main').value=c.main;document.getElementById('rule-indices').value=c.indices.join(',');document.getElementById('rule-indices').disabled=c.main!=='custom';document.getElementById('rule-details').checked=c.details;document.getElementById('rule-skus').checked=c.sku_images;document.getElementById('sync-rule').value=r.id;return}
 if(action==='save-sync'){const scope=document.getElementById('sync-scope').value;await api('sync-request',{store:document.getElementById('sync-store').value,scope:{mode:scope,ids:scope==='all'?[]:document.getElementById('sync-ids').value.split('\n').map(x=>x.trim()).filter(Boolean)},rule_id:document.getElementById('sync-rule').value});await loadState();toast('配置已保存，等待连接真实店铺环境');return}
 return await productionActions(action);
}catch(e){toast(e.message)}};
document.addEventListener('change',e=>{if(e.target.id==='rule-main')document.getElementById('rule-indices').disabled=e.target.value!=='custom';if(e.target.id==='sync-scope')document.getElementById('sync-ids').disabled=e.target.value!=='selected'});

window.addEventListener('hashchange',()=>{editingRule=null});
