'use strict';
let online=false, productFocus=null, videoFocus=null;
const selectedProducts=new Set(),selectedAssets=new Set(),selectedVideos=new Set();
let productStatus='all',storeFilter='',assetKind='all',assetSource='',assetRelation='';
const oldActions=actions,oldRender=render,oldSave=save,oldSettings=settingsPage,oldHome=home;
async function api(name,payload){const response=await fetch('/api/'+name,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const r=await response.json();if(!response.ok)throw new Error(r.error||'本地服务连接失败');return r}
async function loadState(redraw=true){const snapshot=await api('state');Object.assign(data,snapshot);settings={...settings,...snapshot.settings};online=true;if(redraw)render()}
const getProduct=id=>data.products.find(p=>p.id===id);
const getTask=id=>data.tasks.find(p=>p.id===id);
const getAsset=id=>data.assets.find(p=>p.id===id);
const getVideo=id=>data.videos.find(p=>p.id===id);
const getSku=id=>data.skus?.find(p=>p.id===id)?.name||'—';
const productAssets=id=>(data.links||[]).filter(l=>l.product_id===id).sort((a,b)=>a.position-b.position).map(l=>getAsset(l.asset_id)).filter(Boolean);
const media=(a)=>'/media/asset/'+encodeURIComponent(a.id);
const videoURL=v=>'/media/video/'+encodeURIComponent(v.id);
const statusNames={waiting:'等待中',running:'生产中',done:'已完成',failed:'失败',pending:'待发布',uploading:'上传中',uploaded:'已上传',published:'发布成功'};
const statusBadge=s=>`<span class="status ${esc(s)}">${statusNames[s]||esc(s)}</span>`;
const rowtable=(headers,rows,emptyText='暂无记录')=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}" class="table-empty">${emptyText}</td></tr>`}</tbody></table></div>`;
const check=(kind,id)=>`<input type="checkbox" data-select="${kind}" value="${esc(id)}" aria-label="选择 ${esc(id)}" ${(kind==='product'?selectedProducts:kind==='asset'?selectedAssets:selectedVideos).has(id)?'checked':''}>`;
const searchable=(...fields)=>!query||fields.some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()));
const thumbnail=a=>a?.kind==='image'?`<img class="thumb" src="${media(a)}" alt="${esc(a.name)}">`:icon(a?.kind==='music'?'music':'video');
const bytes=n=>n>1024**3?(n/1024**3).toFixed(1)+' GB':n>1024**2?(n/1024**2).toFixed(1)+' MB':(n/1024).toFixed(1)+' KB';
const pstatus=id=>{const ts=data.tasks.filter(t=>t.product_id===id);return ts.some(t=>t.status==='running')?'running':ts.some(t=>t.status==='waiting')?'waiting':ts.some(t=>t.status==='failed')?'failed':ts.length?'done':'unproduced'};
function updateStorage(){if(!data.storage)return;document.getElementById('storage-caption').textContent=bytes(data.storage.total-data.storage.free)+' / '+bytes(data.storage.total)}
render=function(){oldRender();updateStorage()};
save=async function(){try{await api('settings',settings);toast('默认配置已保存');await loadState(false)}catch(e){toast(e.message)}};
config=function(){const t=templates.find(t=>t.id===settings.template)||templates[0];return panel('当前生产配置',`<div class="field"><label class="label">素材来源</label>${select('source',[['local','本地素材'],['products','商品库'],['tiktok','TikTok 店铺商品']],settings.source)}</div><div class="field"><label class="label">店铺选择</label><select aria-label="店铺选择" disabled><option>${settings.source==='tiktok'?'等待连接店铺':'按选定商品关联'}</option></select></div><div class="field"><label class="label">生产范围</label>${go('选择商品 / 素材',settings.source==='local'?'assets':'products')}</div><p class="note">已选择 ${settings.source==='local'?selectedAssets.size+' 份素材':selectedProducts.size+' 个商品'}</p><label class="label">生产模板</label><a href="#templates" class="selected-template"><div class="mini-frame">${icon('image')}</div><div><h3>${t.name}</h3><span>查看或更换生产规则</span></div>${icon('arrow')}</a><div class="field"><label class="label">视频比例</label><select aria-label="视频比例"><option>9:16 · 1080 × 1920</option></select></div><div class="field"><label class="label">视频时长</label>${select('duration',[['template','跟随模板'],['15','15 秒'],['30','30 秒']],settings.duration)}</div><div class="field"><label class="label">音乐规则</label>${select('music',[['none','不添加音乐'],['auto','从音乐库自动匹配'],['selected','指定音乐素材']],settings.music)}</div><div class="field"><label class="label">输出目录</label><input aria-label="输出目录" readonly value="${esc(data.storage?.output||'')}"></div>${btn('创建生产任务','create-task','primary',false,'play')}`,btn('保存为默认','save-config','link'),'config')};
home=function(){let html=oldHome();if(data.products.length){const start=html.indexOf('<div class="empty compact">');const end=html.indexOf('</section>',start);if(start>=0&&end>start){const cards=`<div class="product-cards">${data.products.slice(-6).reverse().map(p=>{const a=productAssets(p.id).find(a=>a.kind==='image');return `<a class="product-card" href="#products" data-product-focus="${esc(p.id)}">${a?`<img src="${media(a)}" alt="${esc(p.title)}">`:`<div class="asset-thumb">${icon('box')}</div>`}<b>${esc(p.title)}</b><small>${esc(p.id)}</small></a>`}).join('')}</div>`;html=html.slice(0,start)+cards+html.slice(end)}}const oldTable=table(['任务名称','素材来源','对象数量','模板','状态','进度','开始时间','操作'],'尚未创建生产任务');html=html.replace(oldTable,taskRows(data.tasks.slice(-5).reverse()));html=html.replace('生产任务 <span class="note">(0)</span>',`生产任务 <span class="note">(${data.tasks.length})</span>`);return html};
products=function(){const shown=data.products.filter(p=>searchable(p.id,p.title,...(data.skus||[]).filter(s=>s.product_id===p.id).map(s=>s.name))).filter(p=>(!storeFilter||p.store===storeFilter)&&(productStatus==='all'||pstatus(p.id)===productStatus));const p=getProduct(productFocus);const rows=shown.map(p=>`<tr class="${p.id===productFocus?'row-selected':''}"><td>${check('product',p.id)}</td><td>${btn(`<b>${esc(p.id)}</b>`,'focus-product:'+p.id,'row-link')}<span class="row-sub">${esc(p.title)}</span></td><td>${esc(p.store)||'—'}</td><td>${data.skus.filter(s=>s.product_id===p.id).length}</td><td>${productAssets(p.id).length}</td><td>${data.tasks.filter(t=>t.product_id===p.id&&t.status==='done').length}</td><td>${pstatus(p.id)==='unproduced'?'<span class="note">未生产</span>':statusBadge(pstatus(p.id))}</td><td>${btn('管理','focus-product:'+p.id,'link')}</td></tr>`).join('');return heading('商品库','统一管理商品、SKU、关联素材与生成视频',btn('导入商品','import-products','',false,'download')+btn('新建商品','new-product','primary',false,'plus'))+`<div class="toolbar">${search('搜索商品编号、标题或 SKU…')}<div class="filters"><select id="store-filter" aria-label="店铺筛选"><option value="">全部店铺</option>${data.stores.map(s=>`<option ${storeFilter===s?'selected':''}>${esc(s)}</option>`).join('')}</select><select id="production-filter" aria-label="生产状态筛选">${[['all','全部生产状态'],['unproduced','未生产'],['waiting','等待中'],['running','生产中'],['done','已生成'],['failed','失败']].map(([s,n])=>`<option value="${s}" ${productStatus===s?'selected':''}>${n}</option>`).join('')}</select></div></div><div class="split">${panel(`全部商品 <span class="note">(${data.products.length})</span>`,rowtable(['选择','商品编号 / 标题','店铺','SKU','素材','视频','生产状态','操作'],rows,noRecords())+(!data.products.length?empty('添加你的第一个商品','商品可关联多个 SKU、多份素材和多条视频。','box',btn('新建商品','new-product','primary',false,'plus'),'compact'):'')+`<div class="footer-actions"><span>已选择 ${selectedProducts.size} 个商品</span>${btn('创建生产任务','product-tasks','',!selectedProducts.size,'play')}</div>`)}${panel('商品关联信息',p?`<h3>${esc(p.title)}</h3><dl class="detail-list"><dt>商品 ID</dt><dd>${esc(p.id)}</dd><dt>店铺</dt><dd>${esc(p.store)||'—'}</dd><dt>商品链接</dt><dd>${esc(p.url)||'—'}</dd><dt>SKU</dt><dd>${data.skus.filter(s=>s.product_id===p.id).map(s=>esc(s.name)).join('<br>')||'—'}</dd></dl><div class="divider"></div><h3>关联素材 (${productAssets(p.id).length})</h3><div class="detail-assets">${productAssets(p.id).map(a=>thumbnail(a)).join('')}</div><div class="actions">${btn('关联素材','link-assets:'+p.id,'',false,'link')}${btn('编辑商品','edit-product:'+p.id,'')}</div>`:`<div class="detail-empty">${icon('box')}<span>选择商品，查看关联信息</span></div>`)}</div>`};
assets=function(){let shown=data.assets.filter(a=>searchable(a.name)).filter(a=>(tab==='all'||a.kind===tab)&&(!assetSource||a.source===assetSource)&&(!assetRelation||(assetRelation==='linked')===data.links.some(l=>l.asset_id===a.id)));const body=view==='grid'?`<div class="asset-grid">${shown.map(a=>`<article class="asset-card"><div class="asset-thumb">${a.kind==='image'?`<img src="${media(a)}" alt="${esc(a.name)}">`:icon(a.kind==='music'?'music':'video')}</div><div class="asset-meta"><label>${check('asset',a.id)}<span title="${esc(a.name)}">${esc(a.name)}</span></label><small>${bytes(a.size)} · ${a.source==='local'?'本地导入':'店铺下载'}</small>${btn('预览','preview-asset:'+a.id,'link')}</div></article>`).join('')}</div>`:rowtable(['选择','素材名称','类型','来源','关联商品','大小','操作'],shown.map(a=>`<tr><td>${check('asset',a.id)}</td><td>${esc(a.name)}</td><td>${{image:'图片',video:'视频',music:'音乐'}[a.kind]}</td><td>${a.source==='local'?'本地':'店铺'}</td><td>${data.links.filter(l=>l.asset_id===a.id).map(l=>esc(l.product_id)).join(', ')||'未绑定'}</td><td>${bytes(a.size)}</td><td>${btn('预览','preview-asset:'+a.id,'link')}</td></tr>`).join(''),noRecords());return heading('素材中心','图片、视频与音乐统一管理，保留原名，可不绑定商品',btn('导入文件夹','import-folder','',false,'folder')+btn('导入素材','import','primary',false,'plus'))+`<div class="toolbar">${search('搜索素材名称…')}<div class="filters"><select id="asset-source" aria-label="素材来源">${[['','全部来源'],['local','本地导入'],['tiktok','TikTok 下载']].map(([v,n])=>`<option value="${v}" ${assetSource===v?'selected':''}>${n}</option>`).join('')}</select><select id="asset-relation" aria-label="关联状态">${[['','全部关联状态'],['linked','已绑定商品'],['unlinked','未绑定商品']].map(([v,n])=>`<option value="${v}" ${assetRelation===v?'selected':''}>${n}</option>`).join('')}</select><div class="view-toggle">${btn(icon('grid'),'view:grid',view==='grid'?'active':'')}${btn(icon('list'),'view:list',view==='list'?'active':'')}</div></div></div><div class="panel">${tabs([['all','全部素材',data.assets.length],...['image','video','music'].map(k=>[k,{image:'图片',video:'视频',music:'音乐'}[k],data.assets.filter(a=>a.kind===k).length])])}${shown.length?body:empty(query?noRecords():'导入本地生产素材','图片、视频和音乐使用同一素材体系。','folder',btn('导入素材','import','primary',false,'plus'),'wide')}<div class="footer-actions"><span>已选择 ${selectedAssets.size} 份素材</span><div class="actions">${btn('关联商品','assets-link','',!selectedAssets.size,'link')}${btn('创建生产任务','asset-tasks','',!selectedAssets.size,'play')}</div></div></div>`};
function taskRows(tasks){return rowtable(['任务 / 商品','SKU','素材','模板','状态','进度','输出 / 原因','操作'],tasks.map(t=>`<tr><td><b class="row-title">${esc(data.batches.find(b=>b.id===t.batch_id)?.name||t.id)}</b><small class="row-sub">${esc(t.product_id||'独立素材组')}</small></td><td>${esc(getSku(t.sku_id))}</td><td>${JSON.parse(t.assets).length}</td><td>${esc(templates.find(x=>x.id===t.template)?.name||t.template)}</td><td>${statusBadge(t.status)}</td><td><progress class="progress" max="100" value="${t.progress}"></progress>${t.progress}%</td><td><span class="row-sub" title="${esc(t.error||t.output||'')}">${esc(t.error||t.output||'—')}</span></td><td>${t.status==='failed'?btn('重试','retry:'+t.id,'link'):t.status==='done'?go('查看视频','videos','link'):''}</td></tr>`).join(''),noRecords())}
taskPage=function(){return heading('生产任务','每个生产对象 × 每个模板版本，生成独立视频任务',btn('创建生产任务','create-task','primary',false,'plus'))+countStats()+`<div class="panel">${tabs([['all','全部任务',data.tasks.length],...['waiting','running','done','failed'].map(s=>[s,statusNames[s],data.tasks.filter(t=>t.status===s).length])])}<div class="toolbar">${search('搜索任务、商品编号…')}</div>${taskRows(data.tasks.filter(t=>(tab==='all'||t.status===tab)&&searchable(t.product_id,t.id,data.batches.find(b=>b.id===t.batch_id)?.name)).slice().reverse())}</div>`};
const videoTask=v=>getTask(v.task_id);
function publicationRows(){return rowtable(['视频 / 商品','SKU','发布目标','发布状态','失败原因 / 说明','时间','操作'],data.publications.filter(p=>(route!=='publish'||tab==='all'||p.status===tab)&&searchable(p.id,videoTask(getVideo(p.video_id)||{})?.product_id,p.target)).map(p=>{const v=getVideo(p.video_id),t=v&&videoTask(v);return `<tr><td>${esc(t?.product_id||'独立素材视频')}<small class="row-sub">${esc(v?.path||'')}</small></td><td>${esc(getSku(t?.sku_id))}</td><td>${esc(p.target)||'等待连接环境'}</td><td>${statusBadge(p.status)}</td><td><span class="row-sub">${esc(p.error||'—')}</span></td><td>${esc(p.created)}</td><td>${btn('重新执行','','',true,'refresh')}</td></tr>`}).join(''),'暂无发布任务')}
publicationQueue=function(){return panel('发布任务队列',`<p class="note">等待真实环境连接；视频生成成功不会自动标记为发布成功。</p>${publicationRows()}`,go('发布中心','publish','link','arrow'))};
function vstate(v){const ps=data.publications.filter(p=>p.video_id===v.id);return ps.some(p=>p.status==='published')?'published':ps.some(p=>p.status==='failed')?'failed':'pending'}
videoPage=function(){const shown=data.videos.filter(v=>tab==='trash'?v.trashed:!v.trashed&&(tab==='all'||(tab==='published'?vstate(v)==='published':vstate(v)===tab))).filter(v=>{const t=videoTask(v),p=getProduct(t?.product_id);return searchable(t?.product_id,p?.title,getSku(t?.sku_id))});const v=getVideo(videoFocus),t=v&&videoTask(v),p=t&&getProduct(t.product_id);return flow('videos')+heading('视频管理','管理已生成视频，预览、追溯来源并加入发布任务',btn('导出列表','export-videos','',!data.videos.length,'download'))+`<div class="toolbar">${search('搜索商品编号、标题或 SKU…')}${btn('批量加入发布','queue-selected','primary',!selectedVideos.size,'send')}</div><div class="split"><div class="panel">${tabs([['all','全部视频',data.videos.filter(v=>!v.trashed).length],['pending','待发布',data.videos.filter(v=>!v.trashed&&vstate(v)==='pending').length],['published','已发布',data.videos.filter(v=>!v.trashed&&vstate(v)==='published').length],['failed','发布失败',data.videos.filter(v=>!v.trashed&&vstate(v)==='failed').length],['trash','回收站',data.videos.filter(v=>v.trashed).length]])}${rowtable(['选择','预览','商品信息','SKU','时长','生成时间','状态','操作'],shown.map(v=>{const t=videoTask(v),p=getProduct(t.product_id),a=getAsset(JSON.parse(t.assets)[0]);return `<tr class="${videoFocus===v.id?'row-selected':''}"><td>${check('video',v.id)}</td><td>${btn(thumbnail(a),'focus-video:'+v.id,'link')}</td><td><b>${esc(t.product_id||'独立素材组')}</b><small class="row-sub">${esc(p?.title||v.path)}</small></td><td>${esc(getSku(t.sku_id))}</td><td>${v.duration.toFixed(1)} 秒</td><td>${esc(v.created)}</td><td>${v.trashed?'<span class="note">回收站</span>':statusBadge(vstate(v))}</td><td>${v.trashed?btn('恢复','restore:'+v.id,'link'):btn('查看','focus-video:'+v.id,'link')}</td></tr>`}).join(''),noRecords())}${!data.videos.length?empty('生成的视频将显示在这里','视频保留实际使用的素材、模板及任务记录。','video',go('前往生产任务','tasks','','tasks'),'compact'):''}<div class="footer-actions"><span>已选择 ${selectedVideos.size} 个视频</span>${btn('移入回收站','trash-selected','danger',!selectedVideos.size,'trash')}</div></div><div class="panel"><h3>视频预览与关联信息</h3><div class="video-preview">${v?`<video controls preload="metadata" src="${videoURL(v)}"></video>`:icon('play')}</div><dl class="detail-list">${[['商品编号',t?.product_id],['商品标题',p?.title],['SKU',getSku(t?.sku_id)],['模板',templates.find(x=>x.id===t?.template)?.name],['生产任务',t?.id],['生成时间',v?.created],['文件路径',v?data.storage.root+'/'+v.path:null],['商品链接',p?.url]].map(([k,val])=>`<dt>${k}</dt><dd>${esc(val||'—')}</dd>`).join('')}</dl><div class="divider"></div><h3>原始素材 (${t?JSON.parse(t.assets).length:0})</h3><div class="detail-assets">${t?JSON.parse(t.assets).map(getAsset).filter(Boolean).map(thumbnail).join(''):''}</div><div class="actions">${btn('打开文件','open-video:'+(v?.id||''),'',!v,'folder')}${btn('重新生成','regenerate:'+(v?.id||''),'',!v,'refresh')}</div></div></div>${publicationQueue()}`};
publishPage=function(){return heading('发布中心','独立记录上传状态与最终发布结果',`<span class="status waiting">等待连接 TikTok 店铺环境</span>`)+`<div class="info-banner">${icon('clock')}尚未执行真实上传或发布。队列保留到环境接入后继续处理。</div><div class="panel">${tabs([['all','全部任务',data.publications.length],...['pending','uploading','uploaded','published','failed'].map(s=>[s,statusNames[s],data.publications.filter(p=>p.status===s).length])])}<div class="toolbar">${search('搜索商品或发布任务…')}${btn('开始发布','','primary',true,'send')}</div>${publicationRows()}${data.publications.length?'':empty('从视频管理添加发布任务','视频生成与发布状态分别记录。','send',go('选择视频','videos','','video'),'compact')}</div>`};
settingsPage=function(){let html=oldSettings();html=html.replaceAll('disabled placeholder="等待桌面运行环境读取"',`readonly value="${esc(data.storage?.root||'')}"`);html=html.replace(btn('打开输出目录','','',true,'folder'),btn('打开输出目录','open-output','',false,'folder')).replace(btn('清理闲置缓存','','',true,'trash'),btn('清理闲置缓存','cleanup','',false,'trash')).replace('本地文件服务尚未接入，当前不能执行清理。','生产任务运行时禁止清理缓存。').replace('缓存大小由桌面运行环境读取。清理不会影响原始素材。',`当前缓存 ${bytes(data.storage?.cache||0)}，清理不会影响原始素材。`);return html};
const closeModal=()=>document.getElementById('dialog').close();
function productForm(p={}){modal(p.id?'编辑商品':'新建商品',`<div class="two-fields"><div class="field"><label class="label" for="product-id">商品 ID *</label><input id="product-id" required maxlength="150" value="${esc(p.id||'')}" ${p.id?'readonly':''}></div><div class="field"><label class="label" for="store">店铺</label><input id="store" value="${esc(p.store||'')}" placeholder="可留空"></div></div><div class="field"><label class="label" for="product-title">商品标题 *</label><input id="product-title" required maxlength="1000" value="${esc(p.title||'')}"></div><div class="field"><label class="label" for="product-link">商品链接</label><input id="product-link" value="${esc(p.url||'')}" placeholder="可留空"></div><div class="field"><label class="label" for="sku">SKU（每行一个）</label><textarea id="sku">${data.skus.filter(s=>s.product_id===p.id).map(s=>esc(s.name)).join('\n')}</textarea></div><p class="note">已有 SKU 及历史视频关联保留，新填写的 SKU 将追加。</p>`,btn('取消','close')+btn('保存商品','submit-product','primary'))}
function batchModal(){const isProduct=settings.source!=='local';const choices=isProduct?data.products:data.assets.filter(a=>a.kind!=='music');const chosen=isProduct?selectedProducts:selectedAssets;modal('创建批量生产任务',`<div class="field"><label class="label" for="task-name">批次名称</label><input id="task-name" placeholder="例如：本批商品视频"></div><div class="field"><label class="label">生产对象</label><select id="batch-source"><option value="products" ${isProduct?'selected':''}>商品库（每个商品独立生成）</option><option value="local" ${!isProduct?'selected':''}>本地素材（每份素材独立，或选中素材合为一组）</option></select></div><div class="choice-list">${choices.length?choices.map(o=>`<label><input type="checkbox" name="batch-object" value="${esc(o.id)}" ${chosen.has(o.id)?'checked':''}><span>${esc(o.title||o.name)} <small class="note">${isProduct?esc(o.id):''}</small></span>${isProduct?`<select data-sku-for="${esc(o.id)}" aria-label="${esc(o.id)} 的 SKU"><option value="">整个商品 / 不指定 SKU</option>${data.skus.filter(s=>s.product_id===o.id).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select>`:''}</label>`).join(''):'<p class="note">暂无生产对象，请先导入素材或新建商品。</p>'}</div>${!isProduct?'<div class="field"><label class="label">素材分组</label><select id="group-mode"><option value="individual">每份素材生成独立视频</option><option value="group">将所选素材按列表顺序合为一个视频组</option></select></div>':''}<p class="group-label">模板版本（可多选）</p>${templates.map(t=>`<label class="settings-row"><span>${t.name}</span><input type="checkbox" name="batch-template" value="${t.id}" ${settings.template===t.id?'checked':''}></label>`).join('')}<div class="two-fields"><div class="field"><label class="label">时长</label><select id="batch-duration"><option value="template">跟随模板</option><option value="15" ${settings.duration==='15'?'selected':''}>15 秒</option><option value="30" ${settings.duration==='30'?'selected':''}>30 秒</option></select></div><div class="field"><label class="label">音乐</label><select id="batch-music"><option value="none">不添加音乐</option><option value="auto" ${settings.music==='auto'?'selected':''}>从音乐库自动匹配</option>${data.assets.filter(a=>a.kind==='music').map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></div></div><div class="info-banner" id="batch-count"></div>`,btn('取消','close')+btn('创建并开始生产','submit-batch','primary',!choices.length));const count=()=>{let n=document.querySelectorAll('[name=batch-object]:checked').length;if(document.getElementById('group-mode')?.value==='group')n=n?1:0;const m=document.querySelectorAll('[name=batch-template]:checked').length;document.getElementById('batch-count').textContent=`${n} 个生产对象 × ${m} 个模板版本 = ${n*m} 条独立视频任务`};document.querySelectorAll('[name=batch-object],[name=batch-template],#group-mode').forEach(el=>el.addEventListener('change',count));document.getElementById('batch-source').addEventListener('change',e=>{settings.source=e.target.value;closeModal();batchModal()});count()}
actions=async function(action){try{
 if(!online && !action.startsWith('go:')){toast('本地工作空间尚未连接');return}
 if(action==='help'){modal('从商品到视频',`<ol class="rules"><li>在商品库新建或导入商品；本地素材可以不绑定商品。</li><li>导入图片、视频和音乐，按需关联商品。</li><li>选定商品或素材，选择模板创建批量任务。</li><li>在视频管理预览、追溯、重新生成或加入发布队列。</li><li>真实 TikTok 环境接入后再执行同步和发布。</li></ol>`);return}
 if(action.startsWith('focus-product:')){productFocus=action.slice(14);render();return}
 if(action.startsWith('focus-video:')){videoFocus=action.slice(12);render();return}
 if(action==='new-product'){productForm();return}
 if(action.startsWith('edit-product:')){productForm(getProduct(action.slice(13)));return}
 if(action==='submit-product'){const value=id=>document.getElementById(id).value.trim();const id=value('product-id'),title=value('product-title');if(!id||!title){toast('请填写商品 ID 和标题');return}await api('product',{id,title,store:value('store'),url:value('product-link'),skus:value('sku').split('\n')});closeModal();productFocus=id;await loadState();toast('商品已保存');return}
 if(action==='import-products'){modal('导入商品 CSV',`<p class="dialog-description">CSV 表头：id、title、store、url、skus。id 与 title 必填；多个 SKU 使用 | 分隔。相同商品 ID 更新信息并保留历史关联。</p>`,btn('取消','close')+btn('选择 CSV 文件','pick-products','primary',false,'folder'));return}
 if(action==='pick-products'){closeModal();const r=await api('import-products',{});await loadState();toast(`已导入 ${r.count} 个商品`);return}
 if(['import','import-folder'].includes(action)){const r=await api('import',{folder:action==='import-folder'});await loadState();if(r.errors.length){modal('素材导入结果',`<p class="dialog-description">识别 ${r.ids.length} 份有效素材，${r.errors.length} 份未导入。</p><div class="import-result">${r.errors.map(e=>`<p><b>${esc(e.name)}</b><br>${esc(e.error)}</p>`).join('')}</div>`)}else toast(`已识别 ${r.ids.length} 份素材`);return}
 if(action.startsWith('preview-asset:')){const a=getAsset(action.slice(14));modal(esc(a.name),a.kind==='image'?`<img src="${media(a)}" alt="${esc(a.name)}" width="100%">`:a.kind==='music'?`<audio src="${media(a)}" controls></audio>`:`<video src="${media(a)}" controls width="100%"></video>`);return}
 if(action.startsWith('link-assets:')){const pid=action.slice(12);modal('关联素材 · '+esc(pid),`<div class="choice-list">${data.assets.map(a=>`<label><input type="checkbox" name="link-asset" value="${a.id}" ${productAssets(pid).some(x=>x.id===a.id)?'checked disabled':''}><span>${esc(a.name)}</span></label>`).join('')||'<p class="note">请先导入素材。</p>'}</div>`,btn('取消','close')+btn('保存关联','submit-link:'+pid,'primary',!data.assets.length));return}
 if(action.startsWith('submit-link:')){await api('link',{product_id:action.slice(12),ids:[...document.querySelectorAll('[name=link-asset]:checked')].map(e=>e.value)});closeModal();await loadState();toast('素材关联已保存');return}
 if(action==='assets-link'){modal('关联到商品',`<div class="field"><label class="label">目标商品</label><select id="link-product">${data.products.map(p=>`<option value="${esc(p.id)}">${esc(p.id)} · ${esc(p.title)}</option>`).join('')}</select></div><p class="note">将关联 ${selectedAssets.size} 份素材，保留现有商品关系。</p>`,btn('取消','close')+btn('关联','link-selected','primary',!data.products.length));return}
 if(action==='link-selected'){await api('link',{product_id:document.getElementById('link-product').value,ids:[...selectedAssets]});closeModal();await loadState();toast('关联已保存');return}
 if(['create-task','product-tasks','asset-tasks'].includes(action)){if(action==='product-tasks')settings.source='products';if(action==='asset-tasks')settings.source='local';if(settings.source==='tiktok'){toast('等待连接 TikTok 店铺环境');return}batchModal();return}
 if(action==='submit-batch'){const product=document.getElementById('batch-source').value==='products';const ids=[...document.querySelectorAll('[name=batch-object]:checked')].map(e=>e.value);const ts=[...document.querySelectorAll('[name=batch-template]:checked')].map(e=>e.value);if(!ids.length||!ts.length){toast('请选择生产对象和模板');return}const skuFor=id=>[...document.querySelectorAll('[data-sku-for]')].find(e=>e.dataset.skuFor===id)?.value||null;const objects=product?ids.map(id=>({product_id:id,sku_id:skuFor(id)})):document.getElementById('group-mode').value==='group'?[{assets:ids}]:ids.map(id=>({assets:[id]}));const music=document.getElementById('batch-music').value;const payload={name:document.getElementById('task-name').value,objects,templates:ts,duration:document.getElementById('batch-duration').value,music:['auto','none'].includes(music)?music:'selected',music_id:['auto','none'].includes(music)?null:music};const r=await api('batch',payload);closeModal();await loadState();location.hash='tasks';toast(`已创建 ${r.tasks} 条视频任务`);return}
 if(action.startsWith('retry:')){await api('retry',{id:action.slice(6)});await loadState();return}
 if(action.startsWith('regenerate:')){await api('regenerate',{id:action.slice(11)});await loadState();toast('已按原始配置创建新视频任务');return}
 if(action.startsWith('open-video:')){await api('open',{id:action.slice(11)});return}
 if(action==='open-output'){await api('open',{});return}
 if(action==='queue-selected'){for(const id of selectedVideos)await api('queue',{id});await loadState();toast('已加入发布队列，等待连接真实环境');return}
 if(action==='trash-selected'){modal('移入回收站',`<p class="dialog-description">将 ${selectedVideos.size} 条视频移入回收站。输出文件暂时保留，原始素材不受影响。</p>`,btn('取消','close')+btn('移入回收站','confirm-trash','danger'));return}
 if(action==='confirm-trash'){for(const id of selectedVideos)await api('trash',{id});selectedVideos.clear();closeModal();await loadState();return}
 if(action.startsWith('restore:')){await api('trash',{id:action.slice(8),restore:true});await loadState();return}
 if(action==='cleanup'){const r=await api('cleanup',{});await loadState();toast('已清理 '+bytes(r.bytes)+' 缓存');return}
 if(action==='export-videos'){const header=['video_id','product_id','sku','template','task_id','path','created'];const rows=data.videos.map(v=>{const t=videoTask(v);return[v.id,t.product_id,getSku(t.sku_id),t.template,t.id,data.storage.root+'/'+v.path,v.created]});const csv='\ufeff'+[header,...rows].map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='TikTokVideoMaker_videos.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return}
 return await oldActions(action);
}catch(e){toast(e.message)}};
document.addEventListener('change',e=>{const kind=e.target.dataset.select;if(kind){const set=kind==='product'?selectedProducts:kind==='asset'?selectedAssets:selectedVideos;e.target.checked?set.add(e.target.value):set.delete(e.target.value);render()}if(e.target.id==='store-filter'){storeFilter=e.target.value;render()}if(e.target.id==='production-filter'){productStatus=e.target.value;render()}if(e.target.id==='asset-source'){assetSource=e.target.value;render()}if(e.target.id==='asset-relation'){assetRelation=e.target.value;render()}});
document.addEventListener('click',e=>{const a=e.target.closest('[data-product-focus]');if(a)productFocus=a.dataset.productFocus});
// Refresh only when the user is not editing, selecting, viewing a modal or playing video.
setInterval(async()=>{if(!['home','tasks','videos','publish'].includes(route)||!online||document.getElementById('dialog').open||document.querySelector('video')||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;try{const before=JSON.stringify(data);await loadState(false);if(before!==JSON.stringify(data))render()}catch(e){toast(e.message)}},2000);
loadState().catch(e=>{online=false;document.getElementById('page').innerHTML=panel('本地工作空间未连接',`<div class="offline"><h3>请从 TikTokVideoMaker 桌面程序启动</h3><p class="note">${esc(e.message)}</p></div>`)});
shops=function(){const rules=data.download_rules||[];return heading('店铺商品','选择店铺与商品范围，应用图片下载规则后同步到统一素材中心',`<span class="status waiting">等待连接 TikTok 店铺环境</span>`)+`<div class="info-banner">${icon('clock')}当前仅保存同步配置。没有连接真实环境，不会采集商品或下载图片。</div><div class="settings-grid">${panel('商品同步配置',`<div class="field"><label class="label" for="sync-store">待连接店铺</label><input id="sync-store" placeholder="填写店铺名称，仅保存配置"></div><div class="field"><label class="label" for="sync-scope">商品范围</label><select id="sync-scope"><option value="all">全部商品</option><option value="selected">指定商品 ID</option></select></div><div class="field"><label class="label" for="sync-ids">指定商品 ID（每行一个）</label><textarea id="sync-ids" disabled placeholder="选择指定商品范围后填写"></textarea></div><div class="field"><label class="label" for="sync-rule">图片下载规则</label><select id="sync-rule">${rules.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')||'<option value="">请先保存图片下载规则</option>'}</select></div><div class="actions">${btn('保存待连接配置','save-sync','primary',!rules.length,'check')}${btn('开始同步','','',true,'download')}</div>`)}${panel('图片下载规则',`<div class="field"><label class="label" for="rule-name">规则名称</label><input id="rule-name" placeholder="例如：手机壳视频素材规则"></div><div class="field"><label class="label" for="rule-main">商品主图</label><select id="rule-main"><option value="first">下载第 1 张主图</option><option value="all">下载全部主图</option><option value="custom">自定义选择</option></select></div><div class="field"><label class="label" for="rule-indices">自定义主图序号</label><input id="rule-indices" disabled placeholder="例如：1,3,5"></div><label class="settings-row"><span>全部详情图片</span><input id="rule-details" type="checkbox" checked></label><label class="settings-row"><span>SKU 图片及对应关系</span><input id="rule-skus" type="checkbox" checked></label><label class="settings-row"><span>商品视频 <small class="note">当前未开放</small></span><input type="checkbox" disabled></label><p class="note">保留商品 ID、SKU ID / 名称、图片类型、排序和来源。后续生产直接使用关联素材。</p>${btn('保存下载规则','save-rule','primary',false,'check')}`)}</div>${panel('已保存的图片规则',rowtable(['规则名称','主图','详情图','SKU 图','商品视频','操作'],rules.map(r=>{const c=JSON.parse(r.config);return `<tr><td>${esc(r.name)}</td><td>${c.main==='first'?'第 1 张':c.main==='all'?'全部主图':'第 '+c.indices.join('、')+' 张'}</td><td>${c.details?'全部':'关闭'}</td><td>${c.sku_images?'开启':'关闭'}</td><td>关闭</td><td>${btn('载入规则','load-rule:'+r.id,'link')}</td></tr>`}).join(''),'尚未保存下载规则'))}${panel('商品同步任务',rowtable(['店铺','商品范围','图片规则','同步状态','创建时间'],(data.sync_tasks||[]).map(t=>{const c=JSON.parse(t.rule_snapshot||'{}'),s=JSON.parse(t.product_scope||'{}');return `<tr><td>${esc(t.store)}</td><td>${s.mode==='all'?'全部商品':esc((s.ids||[]).join('、'))}</td><td>${c.main==='first'?'第 1 张主图':c.main==='all'?'全部主图':esc((c.indices||[]).join('、'))}</td><td><span class="status waiting">等待连接</span></td><td>${esc(t.created)}</td></tr>`}).join(''),'暂无同步配置'))}`};
let editingRule=null;
const productionActions=actions;
actions=async function(action){try{
 if(action==='save-rule'){const mode=document.getElementById('rule-main').value;const text=document.getElementById('rule-indices').value.trim();const indices=mode==='custom'?text.split(/[,，\s]+/).filter(Boolean).map(x=>/^\d+$/.test(x)?Number(x):null):[];if(mode==='custom'&&(!indices.length||indices.some(x=>x===null||!Number.isSafeInteger(x)||x<1))){toast('请输入正整数主图序号，例如 1,3,5');return}await api('download-rule',{id:editingRule,name:document.getElementById('rule-name').value,main:mode,indices,details:document.getElementById('rule-details').checked,sku_images:document.getElementById('rule-skus').checked,product_video:false});editingRule=null;await loadState();toast('图片下载规则已保存');return}
 if(action.startsWith('load-rule:')){const r=data.download_rules.find(r=>r.id===action.slice(10));if(!r)return;editingRule=r.id;const c=JSON.parse(r.config);document.getElementById('rule-name').value=r.name;document.getElementById('rule-main').value=c.main;document.getElementById('rule-indices').value=c.indices.join(',');document.getElementById('rule-indices').disabled=c.main!=='custom';document.getElementById('rule-details').checked=c.details;document.getElementById('rule-skus').checked=c.sku_images;document.getElementById('sync-rule').value=r.id;return}
 if(action==='save-sync'){const scope=document.getElementById('sync-scope').value;await api('sync-request',{store:document.getElementById('sync-store').value,scope:{mode:scope,ids:scope==='all'?[]:document.getElementById('sync-ids').value.split('\n').map(x=>x.trim()).filter(Boolean)},rule_id:document.getElementById('sync-rule').value});await loadState();toast('配置已保存，等待连接真实店铺环境');return}
 return await productionActions(action);
}catch(e){toast(e.message)}};
document.addEventListener('change',e=>{if(e.target.id==='rule-main')document.getElementById('rule-indices').disabled=e.target.value!=='custom';if(e.target.id==='sync-scope')document.getElementById('sync-ids').disabled=e.target.value!=='selected'});

window.addEventListener('hashchange',()=>{editingRule=null});
